Repository team-collabor/coworkers, pull requests merged in 2024-10, with the labels that each got.

#2 docs: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/ISSUE_TEMPLATE/신규-기능.md
Labels: 문서화

#4 docs: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서화

#5 [Feature] Next.js 프로젝트 세팅 및 초기 환경 구성
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/favicon.ico
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/fonts/GeistMonoVF.woff
  src/pages/fonts/GeistVF.woff
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: 문서화, 기능 추가

#6 docs: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/ISSUE_TEMPLATE/신규-기능.md
Labels: 문서화

#12 Feature/7 주요기능 신규 기능 프로젝트 설정
  .eslintrc.json
  .prettierignore
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  public/icons/dummy.txt
  public/images/dummy.txt
  src/apis/practice.txt
  src/components/auth/practice.txt
  src/components/common/practice.txt
  src/components/layouts/RootLayout.tsx
  src/hooks/auth/dummy.txt
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/fonts/GeistMonoVF.woff
  src/pages/fonts/GeistVF.woff
  src/pages/index.tsx
  src/providers/QueryProvider.tsx
  src/providers/practice.txt
  src/queries/practice.txt
  src/store/practice.txt
  src/styles/globals.css
  src/types/dto/requests/practice.txt
  src/types/dto/responses/practice.txt
  src/types/practice.txt
  src/utils/dateTimeUtils/FormatDistanceToNow.ts
  src/utils/utilityTypes/NullablePick.ts
  src/utils/utilityTypes/OptionalPick.ts
  tailwind.config.ts
  tsconfig.json
Labels: 문서화, 기능 추가

#13 Feat: 2024-10-08 Dev to Main
  .eslintrc.json
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .prettierignore
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  public/icons/dummy.txt
  public/images/dummy.txt
  src/apis/practice.txt
  src/components/auth/practice.txt
  src/components/common/practice.txt
  src/components/layouts/RootLayout.tsx
  src/hooks/auth/dummy.txt
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/fonts/GeistMonoVF.woff
  src/pages/fonts/GeistVF.woff
  src/pages/index.tsx
  src/providers/QueryProvider.tsx
  src/providers/practice.txt
  src/queries/practice.txt
  src/store/practice.txt
  src/styles/globals.css
  src/types/dto/requests/practice.txt
  src/types/dto/responses/practice.txt
  src/types/practice.txt
  src/utils/dateTimeUtils/FormatDistanceToNow.ts
  src/utils/utilityTypes/NullablePick.ts
  src/utils/utilityTypes/OptionalPick.ts
  tailwind.config.ts
  tsconfig.json
Labels: 문서화, 기능 추가

#14 chore: tailwind css colors 및 fontSize 수정
  src/styles/globals.css
  tailwind.config.ts
Labels: 기능 추가

#23 feature: 공통img 추가
  public/images/Google.svg
  public/images/Kakaotalk.svg
  public/images/Landing_check.svg
  public/images/Landing_email.svg
  public/images/Landing_folder.svg
  public/images/Landing_mockup_comment.svg
  public/images/Landing_mockup_invite.svg
  public/images/Landing_mockup_list.svg
  public/images/Landing_trafficwork_large.svg
  public/images/Landing_trafficwork_medium.svg
  public/images/Landing_trafficwork_small.svg
  public/images/Landing_trainwork_large.svg
  public/images/Landing_trainwork_medium.svg
  public/images/Landing_trainwork_small.svg
  public/images/Logo_large.svg
  public/images/Logo_small.svg
  public/images/Thumbnail_team.svg
  public/images/Todo.svg
  public/images/WithoutTeam.svg
  public/images/dummy.txt
Labels: 기능 추가

#36 Feature/21 주요기능 공통컴포넌트 인풋 추가
  package-lock.json
  package.json
  public/icons/Calendar.svg
  public/icons/Done.svg
  public/icons/Member.svg
  public/icons/Time.svg
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/pages/preview/index.tsx
  src/pages/preview/input/index.tsx
  src/styles/globals.css
  src/types/common.types.ts
  src/utils/tailwind/Cn.ts
  tailwind.config.ts
Labels: 기능 추가

#40 Feature/39 husky 적용
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  tsconfig.json
Labels: 문서화, 기능 추가

#37 Feature/8 주요기능 공통 컴포넌트 드롭다운 기능 구현
  src/components/common/dropdown.tsx
  src/styles/globals.css
Labels: 기능 추가

#38 Feature/9 공통 컴포넌트 Button 추가
  src/components/common/Button/Button.tsx
Labels: 기능 추가

#46 fix: global css 누락된 중괄호 추가
  src/styles/globals.css
Labels: 버그

#49 feature/ 48 axios instance 추가
  src/apis/_axiosInstance.ts
Labels: 기능 추가

#50 fix: 누락된 export 추가 #48
  src/apis/_axiosInstance.ts
Labels: 버그

#51 Feature/15 회원 기능 추가
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/_axiosInstance.ts
  src/apis/auth.api.ts
  src/components/auth/signin/SignInForm.tsx
  src/components/auth/signin/SignInSection.tsx
  src/components/auth/signup/SignUpForm.tsx
  src/components/auth/signup/SingUpSection.tsx
  src/components/layouts/RootLayout.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/queries/auth.queries.ts
  src/queries/practice.txt
  src/store/practice.txt
  src/store/useAuthStore.ts
  src/types/auth.types.ts
  src/types/common.types.ts
  src/types/dto/requests/auth.request.types.ts
  src/types/dto/responses/auth.response.types.ts
Labels: 기능 추가

#47 Feature/35 Badge 컴포넌트 추가
  public/icons/Check_lightGreen.svg
  src/components/common/Badge.tsx
Labels: 기능 추가

#52 Hotfix/axios 인터셉터 수정
  src/apis/_axiosInstance.ts
Labels: 버그

#54 Feature/32 신규 기능 모달 컴포넌트 기능 개발
  src/components/modal/index.ts
  src/components/modal/model/modal.context.ts
  src/components/modal/ui/modal.content.tsx
  src/components/modal/ui/modal.header.tsx
  src/components/modal/ui/modal.overlay.tsx
  src/components/modal/ui/modal.portal.tsx
  src/components/modal/ui/modal.root.tsx
  src/components/modal/ui/modal.summary.tsx
  src/components/modal/ui/modal.title.tsx
  src/components/modal/ui/modal.toggle.tsx
  src/components/next/index.ts
  src/components/next/ui/unoptimized.image.tsx
  src/hooks/context/use-context-selector.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 기능 추가

#57 Fix/dropdown 공통컴포넌트 이벤트 문제 해결
  src/components/common/dropdown.tsx
  src/pages/preview/dropdown/index.tsx
Labels: 기능 추가

#53 Feature/25 주요기능 신규 기능 팀 생성하기 기능
  package-lock.json
  package.json
  src/apis/groups.api.ts
  src/pages/addteam/index.tsx
  src/queries/groups.queries.ts
  src/styles/globals.css
  src/types/team.tsx
Labels: 기능 추가

#59 Feature/윈도우 반응형 훅
  src/constants/mediaQueryBreakPoint.ts
  src/hooks/useIsMobile.ts
Labels: 기능 추가

#58 Feature/22 신규 기능 자유게시판 페이지
  package-lock.json
  package.json
  src/apis/article.api.ts
  src/apis/practice.txt
  src/components/board/AllArticlesSection.tsx
  src/components/board/ArticleCard.tsx
  src/components/board/BestArticleCard.tsx
  src/components/board/BestArticlesSection.tsx
  src/pages/boards/index.tsx
  src/queries/article.queries.ts
  src/types/dto/requests/article.request.types.ts
  src/types/dto/responses/article.response.types.ts
  src/types/practice.txt
  src/utils/dateTimeUtils/FormatData.ts
  tailwind.config.ts
Labels: 기능 추가

#66 Fix/code review workflow 수정
  .github/workflows/code-reivew.yml
Labels: 버그

#68 Feature/ 2024-10-16 Dev to Main
  .eslintrc.json
  .github/workflows/code-reivew.yml
  package-lock.json
  package.json
  public/icons/Check_lightGreen.svg
  src/apis/_axiosInstance.ts
  src/apis/article.api.ts
  src/apis/auth.api.ts
  src/apis/groups.api.ts
  src/apis/practice.txt
  src/components/auth/signin/SignInForm.tsx
  src/components/auth/signin/SignInSection.tsx
  src/components/auth/signup/SignUpForm.tsx
  src/components/auth/signup/SingUpSection.tsx
  src/components/board/AllArticlesSection.tsx
  src/components/board/ArticleCard.tsx
  src/components/board/BestArticleCard.tsx
  src/components/board/BestArticlesSection.tsx
  src/components/common/Badge.tsx
  src/components/common/dropdown.tsx
  src/components/layouts/RootLayout.tsx
  src/components/modal/index.ts
  src/components/modal/model/modal.context.ts
  src/components/modal/ui/modal.content.tsx
  src/components/modal/ui/modal.header.tsx
  src/components/modal/ui/modal.overlay.tsx
  src/components/modal/ui/modal.portal.tsx
  src/components/modal/ui/modal.root.tsx
  src/components/modal/ui/modal.summary.tsx
  src/components/modal/ui/modal.title.tsx
  src/components/modal/ui/modal.toggle.tsx
  src/components/next/index.ts
  src/components/next/ui/unoptimized.image.tsx
  src/constants/mediaQueryBreakPoint.ts
  src/hooks/context/use-context-selector.ts
  src/hooks/useIsMobile.ts
  src/pages/addteam/index.tsx
  src/pages/boards/index.tsx
  src/pages/preview/dropdown/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/queries/article.queries.ts
  src/queries/auth.queries.ts
  src/queries/groups.queries.ts
  src/queries/practice.txt
  src/store/practice.txt
  src/store/useAuthStore.ts
  src/styles/globals.css
  src/types/auth.types.ts
  src/types/common.types.ts
  src/types/dto/requests/article.request.types.ts
  src/types/dto/requests/auth.request.types.ts
  src/types/dto/responses/article.response.types.ts
  src/types/dto/responses/auth.response.types.ts
  src/types/practice.txt
  src/types/team.tsx
  src/utils/dateTimeUtils/FormatData.ts
  tailwind.config.ts
Labels: 버그, 기능 추가

#69 Fix/ code-review worflow 프롬프트 제거
  .github/workflows/code-reivew.yml
Labels: 버그

#70 Fix/ 2024-10-16 Dev to Main
  .github/workflows/code-reivew.yml
Labels: 버그

#67 Feature/15 회원 기능 개선
  .eslintrc.json
  .github/workflows/code-reivew.yml
  package-lock.json
  package.json
  src/apis/_axiosInstance.ts
  src/apis/auth.api.ts
  src/components/auth/practice.txt
  src/components/auth/signin/SignInForm.tsx
  src/components/auth/signup/SignUpForm.tsx
  src/components/common/practice.txt
  src/providers/practice.txt
  src/queries/auth.queries.ts
  src/store/useAuthStore.ts
  src/types/dto/requests/practice.txt
  src/types/dto/responses/auth.response.types.ts
  src/types/dto/responses/practice.txt
Labels: 기능 추가

#74 Feature/73 신규 기능 환경 변수 추가
  src/apis/_axiosInstance.ts
  src/styles/globals.css
Labels: 기능 추가

#77 Feature/75 user 및 user membership 데이터 가져오기 및 상태 관리 기능 추가
  src/apis/users.api.ts
  src/queries/auth.queries.ts
  src/queries/keys/auth.keys.ts
  src/queries/keys/users.keys.ts
  src/queries/users.queries.ts
  src/store/useAuthStore.ts
  src/types/auth.types.ts
  src/types/dto/responses/auth.response.types.ts
  src/types/dto/responses/users.response.types.ts
  src/types/groups.types.ts
  src/types/users.types.ts
Labels: 기능 추가

#81 Feature/80 공통컴포넌트 Toast 추가
  components.json
  package-lock.json
  package.json
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/Toaster.tsx
  src/components/layouts/RootLayout.tsx
  src/hooks/useToast.ts
  src/pages/preview/index.tsx
  src/pages/preview/toast/index.tsx
  src/utils/tailwind/cn.ts
  tailwind.config.ts
Labels: 기능 추가

#83 Fix/ AllArticlesSection 컴포넌트 Dropdown 참조 오류 수정
  src/components/board/AllArticlesSection.tsx
Labels: 버그

#82 Feature/ 2024-10-18 Dev to Main
  .eslintrc.json
  .github/workflows/code-reivew.yml
  components.json
  package-lock.json
  package.json
  public/images/Done.svg
  src/apis/_axiosInstance.ts
  src/apis/auth.api.ts
  src/apis/groups.api.ts
  src/apis/users.api.ts
  src/components/TaskList/TaskLists.tsx
  src/components/TaskList/VirtualScroll.tsx
  src/components/Team/Members.tsx
  src/components/Team/Progress.tsx
  src/components/auth/practice.txt
  src/components/auth/signin/SignInForm.tsx
  src/components/auth/signup/SignUpForm.tsx
  src/components/board/AllArticlesSection.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/Toaster.tsx
  src/components/common/practice.txt
  src/components/layouts/RootLayout.tsx
  src/hooks/useIsMobile.ts
  src/hooks/useToast.ts
  src/pages/[id]/index.tsx
  src/pages/preview/dropdown/index.tsx
  src/pages/preview/index.tsx
  src/pages/preview/toast/index.tsx
  src/providers/ChangingProgressProvider.tsx
  src/providers/practice.txt
  src/queries/auth.queries.ts
  src/queries/groups.queries.ts
  src/queries/keys/auth.keys.ts
  src/queries/keys/users.keys.ts
  src/queries/users.queries.ts
  src/store/useAuthStore.ts
  src/styles/globals.css
  src/types/auth.types.ts
  src/types/dto/requests/practice.txt
  src/types/dto/responses/auth.response.types.ts
  src/types/dto/responses/practice.txt
  src/types/dto/responses/users.response.types.ts
  src/types/groups.types.ts
  src/types/team.ts
  src/types/users.types.ts
  src/utils/tailwind/cn.ts
  tailwind.config.ts
Labels: 기능 추가

#76 Feature/60 주요기능 신규 기능 팀 참여하기 페이지 구현
  src/apis/groups.api.ts
  src/components/board/AllArticlesSection.tsx
  src/pages/attendteam/index.tsx
  src/queries/groups.queries.ts
Labels: 기능 추가

#78 Feature/28 신규 기능 자유 게시판 게시물 등록 페이지
  next.config.mjs
  public/icons/Upload_plus.svg
  src/apis/article.api.ts
  src/apis/uploadImage.api.ts
  src/pages/addboard/index.tsx
  src/queries/article.queries.ts
  src/queries/uploadImage.query.ts
  src/types/dto/requests/article.request.types.ts
  src/types/dto/responses/article.response.types.ts
  src/types/dto/responses/uploadImage.response.type.ts
  tsconfig.json
Labels: 기능 추가

#79 Feature/31 랜딩페이지 추가
  public/images/Landing_check.svg
  public/images/Landing_email.svg
  public/images/Landing_folder.svg
  src/pages/index.tsx
  tailwind.config.ts
Labels: 기능 추가

#90 Feature/19 주요기능 목록상세페이지 할일추가기능 추가
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/tasks.api.ts
  src/components/common/Button/Button.tsx
  src/components/common/Carousel.tsx
  src/components/common/DatePicker.tsx
  src/components/common/DatePickerInput.tsx
  src/components/common/IconAndText.tsx
  src/components/common/TextArea.tsx
  src/components/modal/index.ts
  src/components/modal/ui/modal.submit.tsx
  src/components/modal/ui/modal.trigger.tsx
  src/components/task/AddTaskForm.tsx
  src/components/task/AddTaskListModal.tsx
  src/components/task/AddTaskModal.tsx
  src/components/task/TaskFrequencyInput.tsx
  src/components/task/TaskListSelector.tsx
  src/components/task/Tasks.tsx
  src/constants/formSchemas/taskSchema.ts
  src/pages/[id]/tasks/index.tsx
  src/queries/keys/tasks.keys.ts
  src/queries/tasks.queries.ts
  src/types/dto/requests/tasks.request.types.ts
  src/types/dto/responses/tasks.response.types.ts
  src/types/tasks.types.ts
  src/utils/string/truncateString.ts
Labels: 기능 추가

#91 Feature/27 신규 기능 자유게시판 상세페이지
  next.config.mjs
  public/icons/Red_heart.svg
  src/apis/article.api.ts
  src/components/board/AllArticlesSection.tsx
  src/components/board/ArticleCard.tsx
  src/components/board/ArticleComment.tsx
  src/components/board/ArticleCommentForm.tsx
  src/components/board/ArticleCommentList.tsx
  src/components/board/ArticleContent.tsx
  src/components/board/BestArticleCard.tsx
  src/components/common/Button/Button.tsx
  src/pages/addboard/index.tsx
  src/pages/boards/[boardId].tsx
  src/pages/boards/index.tsx
  src/queries/article.queries.ts
  src/queries/keys/article.keys.ts
  src/types/article.types.ts
  src/types/dto/requests/article.request.types.ts
  src/types/dto/responses/article.response.types.ts
Labels: 기능 추가

#94 Feature/20 주요기능 목록상세페이지 편집기능 추가
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/comments.api.ts
  src/apis/tasks.api.ts
  src/apis/users.api.ts
  src/components/auth/resetPassword/SendResetPasswordForm.tsx
  src/components/auth/signin/SignInForm.tsx
  src/components/auth/signin/SignInSection.tsx
  src/components/auth/signup/SignUpForm.tsx
  src/components/common/Avatar.tsx
  src/components/common/CheckableText.tsx
  src/components/common/DatePicker.tsx
  src/components/common/DatePickerInput.tsx
  src/components/common/Dialog.tsx
  src/components/common/Divider.tsx
  src/components/common/Drawer.tsx
  src/components/common/DrawerDialog.tsx
  src/components/common/IconAndText.tsx
  src/components/task/AddTaskForm.tsx
  src/components/task/TaskCard.tsx
  src/components/task/Tasks.tsx
  src/components/task/taskDetail/TaskCommentForm.tsx
  src/components/task/taskDetail/TaskCommentList.tsx
  src/components/task/taskDetail/TaskCommentUpdateForm.tsx
  src/components/task/taskDetail/TaskDetailContent.tsx
  src/components/task/taskDetail/TaskDetailModal.tsx
  src/components/task/taskDetail/TaskUpdateForm.tsx
  src/constants/formSchemas/authSchema.ts
  src/constants/formSchemas/commentSchema.ts
  src/constants/formSchemas/taskSchema.ts
  src/pages/signin/reset-password/index.tsx
  src/queries/comments.queries.ts
  src/queries/keys/comments.keys.ts
  src/queries/keys/tasks.keys.ts
  src/queries/tasks.queries.ts
  src/queries/users.queries.ts
  src/store/useCommentStore.ts
  src/store/useTaskStore.ts
  src/types/comment.types.ts
  src/types/dto/requests/comment.request.types.ts
  src/types/dto/requests/tasks.request.types.ts
  src/types/dto/requests/users.request.types.ts
  src/types/dto/responses/comment.request.types.ts
  src/types/dto/responses/tasks.response.types.ts
  src/types/dto/responses/users.response.types.ts
  tailwind.config.ts
Labels: 기능 추가

#95 Feature/93 버그 자유게시판 상세페이지 버그수정, 게시물 수정삭제 기능추가
  src/apis/article.api.ts
  src/components/board/ArticleComment.tsx
  src/components/board/ArticleCommentList.tsx
  src/components/board/ArticleContent.tsx
  src/components/board/BestArticlesSection.tsx
  src/components/board/EditArticleForm.tsx
  src/pages/addboard/index.tsx
  src/queries/article.queries.ts
  src/queries/keys/article.keys.ts
  src/types/article.types.ts
  src/types/dto/requests/article.request.types.ts
Labels: 버그, 기능 추가

#96 Feature/92 주요기능 신규 기능 팀 페이지 및 드롭다운 관련 추가 기능 개선
  src/components/TaskList/TaskLists.tsx
  src/components/TaskList/VirtualScroll.tsx
  src/components/Team/Members.tsx
  src/components/Team/Pagination.tsx
  src/components/Team/Report.tsx
  src/pages/[id]/editteam/index.tsx
  src/pages/[id]/index.tsx
  src/queries/groups.queries.ts
  src/queries/keys/groups.key.ts
Labels: 기능 추가

#97 Feature/33 신규 기능 마이 히스토리 페이지 개발
  src/apis/users.api.ts
  src/components/modal/ui/modal.content.tsx
  src/components/modal/ui/modal.portal.tsx
  src/components/modal/ui/modal.title.tsx
  src/pages/history/index.tsx
  src/queries/keys/users.keys.ts
  src/queries/users.queries.ts
  src/types/dto/responses/users.response.types.ts
  src/types/temp.types.ts
Labels: 기능 추가

#100 Feature/98 버그 자유게시판게시물 상세페이지게시물추가페이지 에러수정 사항 수정
  src/components/board/AllArticles/AllArticlesSection.tsx
  src/components/board/AllArticles/ArticleCard.tsx
  src/components/board/ArticleComments/ArticleComment.tsx
  src/components/board/ArticleComments/ArticleCommentForm.tsx
  src/components/board/ArticleComments/ArticleCommentList.tsx
  src/components/board/BestArticles/BestArticleCard.tsx
  src/components/board/BestArticles/BestArticlesSection.tsx
  src/components/board/DetailArticle/ArticleContent.tsx
  src/components/board/DetailArticle/EditArticleForm.tsx
  src/pages/boards/[boardId].tsx
  src/pages/boards/index.tsx
Labels: 버그
