Repository team-collabor/coworkers, pull requests merged in 2024-11, with the labels that each got.

#104 Feature/84 신규 기능 개인설정 페이지 추가
  public/icons/Subtract.svg
  src/apis/users.api.ts
  src/components/layouts/ui/header/ui/header.profile.tsx
  src/pages/mypage/index.tsx
  src/types/dto/requests/users.request.types.ts
  src/types/dto/responses/users.response.types.ts
Labels: 기능 추가

#106 Feature/102 추가 기능 및 개선 팀 페이지 오류 개선 및 추가 기능
  src/apis/groups.api.ts
  src/apis/taskList.api.ts
  src/components/TaskList/TaskLists.tsx
  src/components/Team/MemberDropDown.tsx
  src/components/Team/Members.tsx
  src/components/common/Dropdown.tsx
  src/components/task/AddTaskListModal.tsx
  src/hooks/useRedirect.ts
  src/pages/[id]/index.tsx
  src/pages/addteam/index.tsx
  src/pages/attendteam/index.tsx
  src/queries/groups.queries.ts
  src/queries/keys/groups.key.ts
  src/queries/taskList.queries.ts
Labels: 버그, 기능 추가

#108 Feature/103 버그 자유게시판 오류 수정
  src/components/board/AllArticles/AllArticlesSection.tsx
  src/components/board/AllArticles/ArticleCard.tsx
  src/components/board/ArticleComments/ArticleComment.tsx
  src/components/board/ArticleComments/ArticleCommentForm.tsx
  src/components/board/BestArticles/BestArticleCard.tsx
  src/components/board/DetailArticle/ArticleContent.tsx
  src/pages/addboard/index.tsx
  src/pages/boards/[boardId].tsx
  src/pages/boards/index.tsx
Labels: 버그

#109 Fix/101 수정 할일목록페이지 버그수정
  src/components/TaskList/TaskLists.tsx
  src/components/common/DatePicker.tsx
  src/components/task/AddTaskForm.tsx
  src/components/task/TaskListSelector.tsx
  src/components/task/Tasks.tsx
  src/components/task/taskDetail/TaskCommentForm.tsx
  src/components/task/taskDetail/TaskCommentList.tsx
  src/components/task/taskDetail/TaskDetailContent.tsx
  src/constants/task/task.ts
  src/pages/[id]/tasks/index.tsx
  src/queries/comments.queries.ts
  src/queries/tasks.queries.ts
  src/types/dto/requests/comment.request.types.ts
Labels: 버그

#110 Fix/107 회원가입페이지 버그 수정
  src/components/auth/signup/SignUpForm.tsx
  src/constants/formSchemas/authSchema.ts
  src/queries/auth.queries.ts
  src/queries/users.queries.ts
  src/store/useAuthStore.ts
Labels: 버그

#115 Fix/105 버그 랜딩페이지 로그인 문제
  src/pages/index.tsx
Labels: 버그

#113 Feature/111 버그 헤더 사이드바 마이 히스토리 버그 및 리팩토링
  src/components/layouts/ui/aside/ui/aside.main.tsx
  src/components/layouts/ui/aside/ui/aside.nav.tsx
  src/components/layouts/ui/header/ui/header.main.tsx
  src/components/layouts/ui/header/ui/header.menu.tsx
  src/components/layouts/ui/header/ui/header.nav.tsx
  src/components/layouts/ui/membership/GroupAddButton.tsx
  src/components/layouts/ui/membership/GroupDeleteModal.tsx
  src/components/layouts/ui/membership/MembershipItem.tsx
  src/components/modal/ui/modal.content.tsx
  src/components/modal/ui/modal.portal.tsx
  src/pages/history/index.tsx
  src/pages/history/ui/NoneHistory.tsx
Labels: 버그

#121 Feature/117 신규 기능 자유게시판 게시물 리스트 스켈레톤 UI추가 & 추가 오류 개선
  src/components/board/AllArticles/AllArticlesSection.tsx
  src/components/board/ArticleComments/ArticleComment.tsx
  src/components/board/ArticleComments/ArticleCommentForm.tsx
  src/components/board/BestArticles/BestArticlesSection.tsx
  src/components/board/DetailArticle/ArticleContent.tsx
  src/components/board/DetailArticle/EditArticleForm.tsx
  src/components/board/Skeleton/ArticleCardSkeleton.tsx
  src/components/board/Skeleton/ArticleContentSkeleton.tsx
  src/pages/addboard/index.tsx
  src/pages/boards/index.tsx
Labels: 버그, 기능 추가

#120 Fix/추가기능/116 신규 기능 팀 페이지 추가 오류 개선
  src/components/TaskList/TaskLists.tsx
  src/components/Team/Members.tsx
  src/hooks/useRedirect.ts
  src/pages/404.tsx
  src/pages/[id]/index.tsx
  src/queries/groups.queries.ts
  src/queries/taskList.queries.ts
  src/queries/users.queries.ts
Labels: 버그

#125 Fix/124 할일목록페이지 할일삭제 모달 위치 수정
  src/components/task/DeleteTaskModal.tsx
  src/components/task/TaskCard.tsx
  src/components/task/Tasks.tsx
  src/pages/[id]/tasks/index.tsx
  src/store/useTaskStore.ts
Labels: 버그

#131 Fix/128개선-버그-팀-페이지-모바일-환경-버그-수정
  src/components/TaskList/TaskLists.tsx
  src/pages/[id]/index.tsx
  src/queries/groups.queries.ts
Labels: 버그

#133 Feature/111 버그 헤더 사이드바 마이 히스토리 버그 및 리팩토링
  src/components/layouts/ui/aside/ui/aside.main.tsx
  src/components/layouts/ui/aside/ui/aside.nav.tsx
  src/components/layouts/ui/header/ui/header.main.tsx
  src/components/layouts/ui/header/ui/header.nav.tsx
  src/components/layouts/ui/header/ui/header.profile.tsx
  src/components/layouts/ui/membership/MembershipItem.tsx
Labels: 버그

#132 Feature/126 신규 기능 자유게시판 게시물 검색 정렬 유지 기능 추가
  src/components/board/AllArticles/AllArticlesSection.tsx
  src/components/board/AllArticles/ArticleCard.tsx
  src/components/board/ArticleComments/ArticleComment.tsx
  src/components/board/ArticleComments/ArticleCommentForm.tsx
  src/components/board/BestArticles/BestArticleCard.tsx
  src/components/board/DetailArticle/ArticleContent.tsx
  src/components/board/DetailArticle/EditArticleForm.tsx
  src/pages/addboard/index.tsx
  src/pages/boards/index.tsx
  src/queries/article.queries.ts
  src/store/useBoardStore.ts
  src/types/article.types.ts
Labels: 버그, 기능 추가

#130 fix:개인설정페이지 이미지및토스트 수정
  public/icons/Edit.svg
  src/pages/mypage/index.tsx
Labels: 버그

#134 Fix/129 할일목록페이지 모바일 버그 수정
  src/components/common/Avatar.tsx
  src/components/common/DatePicker.tsx
  src/components/common/DatePickerInput.tsx
  src/components/common/Drawer.tsx
  src/components/common/DrawerDialog.tsx
  src/components/layouts/ui/aside/ui/aside.nav.tsx
  src/components/task/AddTaskForm.tsx
  src/components/task/DeleteTaskModal.tsx
  src/components/task/Tasks.tsx
  src/components/task/taskDetail/TaskCommentList.tsx
  src/components/task/taskDetail/TaskDetailContent.tsx
  src/queries/tasks.queries.ts
  src/store/useTaskStore.ts
  src/utils/dateTimeUtils/FormatData.ts
  src/utils/dateTimeUtils/addNineHours.ts
Labels: 버그

#142 Feature/137 신규 기능 404 500 에러페이지 추가
  src/components/board/Skeleton/ArticleContentSkeleton.tsx
  src/components/task/Tasks.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/[id]/index.tsx
  tailwind.config.ts
Labels: 기능 추가

#138 Fix/136 버그 badge 00 일 때 표시 추가
  src/components/common/Badge.tsx
Labels: 버그

#135 Fix/105 버그 랜딩페이지 로그인 문제
  src/pages/[id]/index.tsx
  src/pages/index.tsx
  src/pages/withoutteam/index.tsx
Labels: 버그

#139 Feature/16 주요기능 소셜 로그인 추가
  next.config.mjs
  package-lock.json
  package.json
  src/apis/auth.api.ts
  src/components/auth/signin/SignInSection.tsx
  src/components/auth/signin/SocialSignInBox.tsx
  src/components/layouts/ui/header/ui/header.profile.tsx
  src/constants/auth/authUrl.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].js
  src/pages/api/auth/kakaoLogin.ts
  src/providers/OAuthProvider.tsx
  src/queries/auth.queries.ts
  src/queries/keys/auth.keys.ts
  src/store/useAuthStore.ts
  src/types/dto/requests/auth.request.types.ts
  src/types/next-auth.d.ts
  src/utils/string/randomString.ts
  tsconfig.json
Labels: 기능 추가

#145 Feature/144 신규 기능 헤더 팀이미지 프로필이미지 수정
  src/components/layouts/ui/header/ui/header.nav.tsx
  src/components/layouts/ui/header/ui/header.profile.tsx
Labels: 버그, 기능 추가

#149 fix: 카카오 간편로그인 redirect Uri 수정 #143
  src/pages/api/auth/[...nextauth].js
Labels: 버그

#148 Fix/146 버그 멤버 영역 반응형 오류 및 드롭다운 수정
  src/components/Team/MemberDropDown.tsx
  src/components/Team/Members.tsx
Labels: 버그

#152 fix : 151 로그아웃 시 401 에러 방지를 위해 useGetUser를 useAuthStore로 교체
  src/pages/index.tsx
Labels: 버그

#153 fix : 로그아웃 시 401 에러 방지를 위해 useGetUser를 useAuthStore로 교체 to Main
  src/pages/index.tsx
Labels: 버그

#155 fix: 154 사이드 nav bar 수정
  src/components/layouts/ui/membership/MembershipItem.tsx
Labels: 버그

#156 Feature/ 2024-11-08 Dev to Main
  src/components/layouts/ui/membership/MembershipItem.tsx
Labels: 버그, 기능 추가

#157 Feat/119 신규 기능 메타데이터 추가작업
  public/favicon.ico
  public/images/Homepage_img.png
  src/components/auth/signin/SignInForm.tsx
  src/components/auth/signup/SignUpForm.tsx
  src/components/layouts/RootLayout.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/[id]/editteam/index.tsx
  src/pages/[id]/index.tsx
  src/pages/[id]/tasks/index.tsx
  src/pages/addboard/index.tsx
  src/pages/addteam/index.tsx
  src/pages/attendteam/index.tsx
  src/pages/boards/[boardId].tsx
  src/pages/boards/index.tsx
  src/pages/history/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/withoutteam/index.tsx
Labels: 기능 추가
